### ISSUE TITLE
Stand alone ESP8266 example

### ISSUE THREAD

**Issue by goRaspy** [matth-x/ESP8266-OCPP#1]
Thank you so much for your work here.
It is very interesting that you prove the concept of a working implementation of OCCP on ESP8266.

Unfortunately I am not able to make my own tests due of missing external charging point. 
I think, it should be very helpful to dispose of a working example of a stand alone ESP8266 without external hardware.

The example may "just" do the following sequence : 
On boot
- Open web sockets
- Boot notification 
- Send a status notification on a "virtual" connector 1 

On loop : 
- Ping pong for the web socket
- Heartbeat

This example probably needs a specific EVSE.h.

Any help will be highly appreciated.

**Comment by matth-x** [comment]
Hey, thank you for your input!

Actually, the two files in the example folder are a full test routine which runs without external hardware. Just execute the code on your ESP8266 and see in the console what happens! In the test routine, the ESP8266 establishes a connections to a websocket-echo server (`wss://echo.websocket.org`) and performs a full (virtual) EV plug, power scheduling und unplugging cycle.

Before compiling, you have to adapt lines 41 and 42 in example_client.cpp according to your WiFi:
`#define STASSID "YOUR_WLAN_SSID"`
`#define STAPSK  "YOUR_WLAN_PSWD"`

**Comment by goRaspy** [comment]
Thank you so much for your fast feedback.

Unfortunately I was not able to compile. Do you use Arduino IDE to build ? 

Will try again soon.

**Comment by matth-x** [comment]
Mostly PlatformIO, for testing I also use Arduino IDE. What's the error message?

**Comment by goRaspy** [comment]
Hello, sorry for long time answer. I'll look further later. But I would like to ask you if you should be interested to work on an ocpp implementation on a son off device (esp8266 based) ? I can imagine remunerate you.

Many thanks

**Comment by matth-x** [comment]
I would be excited to hear more about your project idea! Sure, provide me with contact details so you can tell me more

**Comment by goRaspy** [comment]
Awesome. Please send me a short email to romain "at" farelle.com

**Comment by vikramec08** [comment]
hi , 
i have tried your code and getting error 
Regards
